name: Java CI with Maven

on:
  workflow_dispatch:
    
  #push:
  #  branches: [ "master" ]
  #pull_request:
  #  branches: [ "master" ]

jobs:
  Build_Maven:
    runs-on: ubuntu-latest

    steps:
      - name: CheckOut
        uses: actions/checkout@v3
        
      - name: Setup Maven
        uses: stCarolas/setup-maven@v.4.5
        with:
         maven-version: 3.8.7

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
       
      # This step generate a war file
      - name: Build with Maven
        run: mvn -B package --file pom.xml 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - uses: actions/upload-artifact@v3
        with:
          name: SHACL-PLAY
          path: ${{ github.workspace }}/shacl-play/target/shacl-play-0.6.2.war
      
      - name: Send a war file to Server SHACL-PLAY scp
        run: scp -i ${{ secrets.SERVER_SSH_KEY }} ${{ github.workspace }}/shacl-play/target/shacl-play-0.6.2.war ${{ secrets.SSH_USER }}@${{ secrets.HOST }}:~
        
        #uses: garygrossgarten/github-action-scp@release
        #with:
        #  local: ${{ github.workspace }}/shacl-play/target/shacl-play-0.6.2.war
        #  remote: "~"
        #  host: ${{ secrets.HOST }}
        #  privateKey: ${{ secrets.SERVER_SSH_KEY }}          
        #  username: ${{ secrets.SSH_USER }}
