name: Java CI with Maven

on:
  workflow_dispatch:
    
  #push:
  #  branches: [ "master" ]
  #pull_request:
  #  branches: [ "master" ]

jobs:
  Build_Maven:
    runs-on: ubuntu-latest

    steps:
      - name: CheckOut
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: ${{ github.ACTOR }}
          server-password: ${{ github.token }}
          settings-path: ${{ github.workspace }} # location for the settings.xml file
                  

      # This step generate a war file
      - name: Build with Maven
        run: mvn -B package --file pom.xml 
      
      - name: Artifact download
        uses: actions/download-artifact@v3
        with:
          name: target

      - name: Display structure of downloaded files
        run: ls -R

  Publish:
    #needs: Build_Maven
    runs-on: ubuntu-latest
    
    steps:
    
      - name: CheckOut
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: ${{ github.ACTOR }}
          server-password: ${{ github.token }}
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Artifact download
        uses: actions/download-artifact@v3
        with:
          name: target

      - name: Display structure of downloaded files
        run: ls -R
    
    #- name: Create GitHub Release
    #  uses: actions/create-release@v1
    #  env:
    #    GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} 
    #  with: 
    #    tag_name: v${{github.run_number}}
    #    release_name: Release V${{github.run_number}}
        
    #- name: Update version
    #  run: mvn -B versions:set -DnewVersion=v${{github.run_number}} -DgenerateBackupPoms=false
    
    #- name: Publish to GitHub Packages Apache Maven
    #  run: mvn -B deploy -DskipTests --file pom.xml
    #  env:
    #    GITHUB_TOKEN: ${{ github.token }}
