# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package & Publish

on:
  workflow_dispatch:
    
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'oracle'
        cache: maven
    
    - name: Build with Maven
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn -B package --file pom.xml
    
    - name: Created folder
      run: mkdir ${{ github.workspace }}/target && cp target/*.jar ${{ github.workspace }}/target
    
    # Upload Target Folder - This step uploads target folder so it could be used in further steps for generating reports.
    - name: Upload target folder
      uses: actions/upload-artifact@v2
      with:
        name: target
        path: |
          ${{ github.workspace }}/target
        if-no-files-found: error
